baseURL: https://unschooled.life/
languageCode: en-us
title: "Unschooled Life"
theme: "PaperMod"
version: 0.1

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: development
  title: "Unschooled Life"
  description: "A collection of learnings."
  keywords: [Blog]
  author: lukefilewalker
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  layout: grid
  width: wide

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    #safari_pinned_tab: "/safari-pinned-tab.svg"

  #cliLabel:
  #  text: lukefilewalker
  label:
    text: "Unschooled Life"
    icon: /favicon-32x32.png
    iconHeight: 35

  #homeInfoParams:
  #  Title: "Greetings! \U0001F62C"
  #  Content: A collection of learnings.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/claude_muller"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: "https://github.com/claudemuller/unschooled.life/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags
  category: categories

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: searchtags
      name: Search
      url: /search/
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai